Script started on Mon 13 Sep 2021 01:39:47 PM CDT
[?1034hbash-4.2$ pwd
/home/u1/mlb0119/cs161/root
bash-4.2$ pwdexit./sys161 kernel[C[C[C[C[C[C[C[C[C[C[8Pcd root[4Ppwdexitmakecd ~/cs161/src/[C[C[C[C[C[C[C[C[C[C[3Pmake install[C[C[C[C[C[C[C[C[C[Ccd ~/cs161/src/[C[C[C[C[C[C[C[C[C[Cmake[Kexit[1Ppwdcd root./sys161 kernel[C[C[C[C[C[C[C[C[C[Cexit[K[1Ppwd[Kcat ~/cs161/src/kern/conf/conf.kern | grep "hello"
file 	  main/hello.c
bash-4.2$ ./sys161 kernel
sys161: System/161 release 1.14, compiled Sep 12 2021 22:36:03

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #2)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

Hello World
OS/161 kernel [? for menu]: p /sbin/poweroff
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 359776381 cycles (4573206k, 18u, 355203157i)
sys161: 2086 irqs 6 exns 0r/0w disk 17r/670w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 14.379009 seconds (25.0209 mhz)
sys161: Elapsed virtual time: 14.391055240 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Mon 13 Sep 2021 01:40:38 PM CDT
