Script started on Mon 13 Sep 2021 01:16:23 PM CDT
[?1034hbash-4.2$ pwd
/home/u1/mlb0119/cs161
bash-4.2$ cd root
bash-4.2$ ./sys161 kernell[K
sys161: System/161 release 1.14, compiled Sep 12 2021 22:36:03

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 1340159477 cycles (10504588k, 18u, 1329654871i)
sys161: 5976 irqs 6 exns 0r/0w disk 18r/658w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 53.593472 seconds (25.006 mhz)
sys161: Elapsed virtual time: 53.606379080 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Mon 13 Sep 2021 01:17:56 PM CDT
